config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: "articles#index"

  get '/articles', to: redirect('/')

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments, only: [:create]
  end  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 200000 }
  has_many :comments, dependent: :destroy
  belongs_to :user, optional: true
  
  def subject
    title
  end

  def last_comment
    comments.last
  end  
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 4000 }
  belongs_to :article
  belongs_to :user, optional: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  
  def index
    @articles = Article.all.order("updated_at DESC")
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    
    if @article.save
        redirect_to @article
    else
      render action: 'new'
    end 
  end

  def edit
    @article = Article.find(params[:id])

    if current_user.id != @article.user_id
      @articles = Article.all.order("updated_at DESC")

      render action: 'index'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end 
  end

  def destroy
    @article = Article.find(params[:id])

    if current_user.id != @article.user_id
      @articles = Article.all.order("updated_at DESC")

      render action: 'index'
    else
      @article.destroy
      redirect_to articles_path
    end
  end  

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:create]
  
  def create
     @article = Article.find(params[:article_id])
     @comment = @article.comments.create(author: current_user.username, user_id: current_user.id, body: comment_params[:body])

     redirect_to article_path(@article)

  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end   

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new

  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end 
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end 
  
  def about
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1><%= t("articles.edit") %></h1>

<%= form_for :article, url: article_path(@article), method: :put, data: { turbo: false } do |f| %>

	<div class="form-group mb-3">
		<%= f.label :title, style: 'display: block' %>
		<%= f.text_field :title, class: 'form-control form-control-lg' %>
	</div>

	<div class="form-group mb-3">
		<%= f.label :text, style: 'display: block' %>
		<%= f.text_area :text, class: 'form-control form-control-lg' %>
	</div>

	<div class="form-group mb-3">
		<%= f.submit class: 'btn btn-primary btn-lg' %>
	</div>	
		
<% end %>	

app/views/articles/index.html.erb
<% @articles.each do |article| %>

<h2>
	<%= article.title %>
</h2>

<p>
	<%= article.text %>
</p>

<p>
	<%= link_to 'Show', article_path(article) %>

	<% if user_signed_in? && current_user == article.user %>
		| <%= link_to 'Edit', edit_article_path(article) %>
		| <%= link_to 'Delete', article_path(article), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
	<% end %>
</p>

<hr />

<% end %>

app/views/articles/new.html.erb
<h1><%= t("articles.new") %></h1>

<%= form_for :article, url: articles_path, data: { turbo: false } do |f| %>

	<div class="form-group mb-3">
		<%= f.label :title, style: 'display: block' %>
		<%= f.text_field :title, class: 'form-control form-control-lg' %>
	</div>

	<div class="form-group mb-3">
		<%= f.label :text, style: 'display: block' %>
		<%= f.text_area :text, class: 'form-control form-control-lg' %>
	</div>

	<div class="form-group mb-3">
		<%= f.submit class: 'btn btn-primary btn-lg' %>
	</div>	
		
<% end %>	

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p>

<h2><%= t("comments.comments_header") %></h2>

<p>
<% @article.comments.each do |comment| %>
	
	<p>
	<i><%= comment.author %> said:</i><br />
	<%= comment.body %>
	</p>	

	<hr />
<% end %>
</p>

<h2><%= t("comments.add_comment") %></h2>

<p>
<% if user_signed_in? %>

	<%= form_for([@article, @article.comments.build]) do |f| %>
	
		<div class="form-group mb-3">
			<%= f.label :author %>: <%= current_user.username %> 
		</div>

		<div class="form-group mb-3">
			<%= f.label :comment, style: 'display: block' %>
			<%= f.text_area :body, class: 'form-control form-control-lg' %>
		</div>

		<div class="form-group mb-3">
			<%= f.submit class: 'btn btn-primary btn-lg' %>
		</div>
	<% end %>

<% else %>
	
	<p><%= t("comments.post_comments") %> <%= link_to 'Sign In', new_user_session_path %> <%= t("comments.post_comments_word_or") %> <%= link_to 'Sign Up', new_user_registration_path %></p>	
	
<% end %>
</p>			

app/views/contacts/create.html.erb
<p><%= t("contacts.sent") %></p>

app/views/contacts/new.html.erb
<h1><%= t("contacts.contact_us") %></h1>

<%= form_for :contact, url: contacts_path, data: { turbo: false } do |f| %>

	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	 	</ul>
	</p>
	<% end %>

	<div class="form-group mb-3">
		<%= f.label :email, style: 'display: block' %>
		<%= f.text_field :email, class: 'form-control form-control-lg' %>
	</div>


	<div class="form-group mb-3">
		<%= f.label :message, style: 'display: block' %>
		<%= f.text_area :message, class: 'form-control form-control-lg' %>
	</div>

	<div class="form-group mb-3">
		<%= f.submit t("contacts.send_message"), class: 'btn btn-primary btn-lg' %>
	</div>	
		
<% end %>	

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="m-4">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to 'My Blog', root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav">
              <li><%= link_to 'Articles', root_path, class: "nav-link" %></li>
              <li><%= link_to 'New article', new_article_path, class: "nav-link" %></li>
              <li><%= link_to 'Contacts', new_contacts_path, class: "nav-link" %></li>
              <li><%= link_to 'About', about_path, class: "nav-link" %></li>
              <li><%= link_to 'Terms', terms_path, class: "nav-link" %></li>
            </ul>

            <ul class="navbar-nav ms-auto">
              <% if user_signed_in? %>
                <li><%= t("layouts.user_greetings") + current_user.username + '!' %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, data:{turbo_method: :delete}, class: "nav-link" %></li>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_path, class: "nav-link" %></li>
              <% end %>  
            </ul>

          </div>
        </div>
      </nav>
    </div> 
 
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>      
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1><%= t("pages.about_us") %></h1>
<p>This is my blog!</p>

app/views/pages/terms.html.erb
<h1><%= t("pages.terms_of_service") %></h1>
<p>This is terms of service!</p>